# Generated by Django 2.1.7 on 2019-03-27 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('cantidad_entregada', models.IntegerField(default=0, verbose_name='Cantidad Entregada')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidoventas',
            name='cantidad_entregada',
        ),
        migrations.AddField(
            model_name='pedidoenvio',
            name='id_envio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedidos.PedidoVentas'),
        ),
    ]
