# Generated by Django 2.1.7 on 2019-03-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_movimiento'),
        ('pedidos', '0003_pedidoventas_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidoventas',
            name='cantidad_pedida',
        ),
        migrations.RemoveField(
            model_name='pedidoventas',
            name='date_des',
        ),
        migrations.RemoveField(
            model_name='pedidoventas',
            name='producto',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='id_pedido',
            field=models.ManyToManyField(to='pedidos.PedidoVentas'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
