# Generated by Django 2.1.7 on 2019-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='segundo',
            field=models.CharField(default=1, max_length=50, verbose_name='claro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tercero',
            field=models.CharField(default=1, max_length=50, verbose_name='tercero'),
            preserve_default=False,
        ),
    ]
