# Generated by Django 2.1.7 on 2019-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20190326_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='Codigo'),
        ),
    ]
