# Generated by Django 2.1.7 on 2019-03-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('n_representante', models.CharField(max_length=100, verbose_name='Nombre del Representante')),
                ('nombre_comercial', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('telefono', models.CharField(max_length=10, verbose_name='No. Telefono')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('mayorista', models.BooleanField(default=False, verbose_name='Mayorista')),
                ('distribuidor', models.BooleanField(default=False, verbose_name='Distribuidor')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('nit', models.CharField(default='C/F', max_length=15, verbose_name='Nit')),
            ],
        ),
    ]
